### PR TITLE
extends BaseController

### PR DESCRIPTION
**Pull request by donnykurnia**
Without this, `php artisan route:list` will failed with error:

    PHP Fatal error:  Call to undefined method Khill\Fontawesome\FontAwesomeController::getMiddleware() in /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php on line 187
    PHP Stack trace:
    PHP   1. {main}() /vagrant/artisan:0
    PHP   2. Illuminate\Foundation\Console\Kernel->handle() /vagrant/artisan:36
    PHP   3. Symfony\Component\Console\Application->run() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
    PHP   4. Symfony\Component\Console\Application->doRun() /vagrant/vendor/symfony/console/Application.php:120
    PHP   5. Symfony\Component\Console\Application->doRunCommand() /vagrant/vendor/symfony/console/Application.php:189
    PHP   6. Illuminate\Console\Command->run() /vagrant/vendor/symfony/console/Application.php:838
    PHP   7. Symfony\Component\Console\Command\Command->run() /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
    PHP   8. Illuminate\Console\Command->execute() /vagrant/vendor/symfony/console/Command/Command.php:256
    PHP   9. Illuminate\Container\Container->call() /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
    PHP  10. call_user_func_array() /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
    PHP  11. Illuminate\Foundation\Console\RouteListCommand->fire() /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
    PHP  12. Illuminate\Foundation\Console\RouteListCommand->getRoutes() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:76
    PHP  13. Illuminate\Foundation\Console\RouteListCommand->getRouteInformation() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:89
    PHP  14. Illuminate\Foundation\Console\RouteListCommand->getMiddleware() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:119
    PHP  15. Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:151
    PHP  16. Illuminate\Foundation\Console\RouteListCommand->getControllerMiddlewareFromInstance() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:171

### CODE REVIEW

**Comment by kevinkhill** [comment]
I might just remove the route and controller altogether. There really isn't a need to have it.

**Comment by 3runoDesign** [comment]
is there any solution?

**Comment by kevinkhill** [comment]
First off, I didn't realize I left this hanging open.
Second, I'm not going to merge because I pulled the controller, route and view from the package.

**Comment by kevinkhill** [comment]
The new tag [1.0.4](https://github.com/kevinkhill/FontAwesomePHP/releases/tag/1.0.4) has the fixes you need to prevent ```php artisan route:list``` from failing.

**Pull request closed without merging**
